options:
  domain:
    description: The local domain for cluster DNS.
    type: string
    default: cluster.local
  forward:
    description: Where to forward non-cluster addresses.
    type: string
    default: /etc/resolv.conf
  extra_servers:
    description: Any additional servers to add to the Corefile.
    type: string
    default: ''
  corefile:
    description: >-
      Configuration file to use for CoreDNS. This is interpreted as a Python
      string.Template which will be given the `domain` and `forward` configs as
      its context.
    type: string
    default: |
      .:53 {
          errors
          health {
            lameduck 5s
          }
          ready
          kubernetes ${domain} in-addr.arpa ip6.arpa {
            fallthrough in-addr.arpa ip6.arpa
            pods insecure
          }
          prometheus :9153
          forward . ${forward}
          cache 30
          loop
          reload
          loadbalance
      }
      ${extra_servers}
